import type { Lang } from './i18n'

const en = {
  greeting: 'Hello, travelers!',
  releaseIntro: 'There are new ways to find your bearings in the wheatfields. This update brings a searchable Controls Guide, a home for settings and support, and a quieter musical companion for the rain.',
  patchIntro: 'This patch brings familiar menu shortcuts back within reach and gives you more control over what you hear. Here is what has changed.',
  features: 'New features and improvements', refinements: 'Improvements', navigation: 'Menus and navigation', audio: 'Audio', guide: 'Controls Guide', support: 'Support',
  audioIntro: 'Let the music lead, or turn it down and listen to the weather. Open the gear, then Sound, to find the new controls.',
  levels: 'Adjust overall volume, music, nature sounds, and sound effects separately. Nature sounds include wind, rain, and distant birds; sound effects include chat chirps and interactions with the painting.',
  mutes: 'Mute each category independently without losing its chosen volume. Overall mute silences everything while keeping your mix ready for when you turn sound back on.',
  saved: 'Sound preferences stay on this device after refreshing the page or changing paintings.',
  shortcuts: 'Change painting and Friends are back below Enter the painting on the main menu. The gear keeps Language, Sound, Flight settings, and Support; Controls Guide remains beside it.',
  articles: 'Changes now has numbered release articles with an overview and sections grouped by topic. Titles show the release type, update number, patch or hotfix number, and release date.',
  closing: 'Thank you for spending time in the wheatfields. If something feels wrong, use “Report an issue” in Support and tell us what happened.',
}
export type ReleaseCopy = Record<keyof typeof en, string>
export const RELEASE_COPY: Record<Lang, ReleaseCopy> = {
  en,
  zhCN: {
    greeting: '旅人们，你们好！',
    releaseIntro: '在麦田里寻找方向，又多了几种方式。这次更新带来了可搜索的操作指南、集中的设置与支持页面，以及陪伴雨声的轻柔配乐。',
    patchIntro: '这次补丁把熟悉的菜单按钮放回了顺手的位置，也让你能更自由地调整声音。以下是具体变更。',
    features: '新增功能与改进', refinements: '功能调整', navigation: '菜单与导航', audio: '声音', guide: '操作指南', support: '支持',
    audioIntro: '让音乐陪你飞行，或把它调低，静听风雨。点齿轮，再进入“声音”，即可找到新的控制选项。',
    levels: '可分别调整总音量、音乐、自然环境声和音效。自然环境声包括风、雨和远处的鸟鸣；音效包括聊天提示音和与画卷互动时的声音。',
    mutes: '每类声音都能单独静音，原来的音量会保留。总静音会关闭所有声音，取消后仍保持你的声音搭配。',
    saved: '刷新页面或切换画卷后，这台设备仍会保留你的声音设置。',
    shortcuts: '“切换画卷”和“好友”已回到主菜单“走进画中”按钮的下方。齿轮里保留语言、声音、飞行设置和支持，操作指南仍在齿轮旁边。',
    articles: '“变更”现在按版本展示文章，先概述更新，再分主题列出详情。标题包含发布类型、更新编号、本次更新内的补丁或紧急修复编号，以及发布日期。',
    closing: '谢谢你来到这片麦田。如果遇到异常，可以通过支持页面的“反馈问题”告诉我们发生了什么。',
  },
  zhTW: {
    greeting: '旅人們，你們好！',
    releaseIntro: '在麥田裡尋找方向，又多了幾種方式。這次更新帶來了可搜尋的操作指南、集中的設定與支援頁面，以及陪伴雨聲的輕柔配樂。',
    patchIntro: '這次修補把熟悉的選單按鈕放回了順手的位置，也讓你能更自由地調整聲音。以下是具體變更。',
    features: '新增功能與改進', refinements: '功能調整', navigation: '選單與導覽', audio: '聲音', guide: '操作指南', support: '支援',
    audioIntro: '讓音樂陪你飛行，或把它調低，靜聽風雨。點齒輪，再進入「聲音」，即可找到新的控制選項。',
    levels: '可分別調整總音量、音樂、自然環境聲和音效。自然環境聲包括風、雨和遠處的鳥鳴；音效包括聊天提示音和與畫卷互動時的聲音。',
    mutes: '每類聲音都能單獨靜音，原來的音量會保留。總靜音會關閉所有聲音，取消後仍保持你的聲音搭配。',
    saved: '重新整理頁面或切換畫卷後，這台裝置仍會保留你的聲音設定。',
    shortcuts: '「切換畫卷」和「好友」已回到主選單「走進畫中」按鈕的下方。齒輪裡保留語言、聲音、飛行設定和支援，操作指南仍在齒輪旁邊。',
    articles: '「變更」現在按版本顯示文章，先概述更新，再分主題列出詳情。標題包含發布類型、更新編號、本次更新內的修補或緊急修復編號，以及發布日期。',
    closing: '謝謝你來到這片麥田。如果遇到異常，可以透過支援頁面的「回報問題」告訴我們發生了什麼。',
  },
  ja: {
    greeting: '旅人のみなさん、こんにちは！',
    releaseIntro: '麦畑での案内がさらに充実しました。今回のアップデートでは、検索できる操作ガイド、設定やサポートの入口、そして雨に寄り添う穏やかな音楽が加わります。',
    patchIntro: '今回のパッチでは、おなじみのメニューボタンを元の場所に戻し、音量をより細かく調整できるようにしました。変更内容をご紹介します。',
    features: '新機能と改善', refinements: '改善', navigation: 'メニューと移動', audio: 'サウンド', guide: '操作ガイド', support: 'サポート',
    audioIntro: '音楽と一緒に飛んだり、音楽を小さくして風雨の音に耳を澄ませたり。歯車から「サウンド」を開くと、新しい調整項目が見つかります。',
    levels: '全体の音量、音楽、自然の音、効果音を個別に調整できます。自然の音には風や雨、遠くの鳥の声が、効果音にはチャットの通知音や絵に触れたときの音が含まれます。',
    mutes: '設定した音量を保ったまま、各項目を個別にミュートできます。全体をミュートしても音量バランスは保存され、解除すると元に戻ります。',
    saved: 'ページを再読み込みしたり、別の絵に移動したりしても、この端末のサウンド設定は保持されます。',
    shortcuts: '「絵を変える」と「ともだち」を、メインメニューの絵に入るボタンの下へ戻しました。歯車には言語、サウンド、飛行設定、サポートが残り、操作ガイドは引き続き歯車の隣にあります。',
    articles: '変更履歴をバージョンごとの記事にまとめ、概要と項目別の説明を掲載しました。タイトルには更新の種類、アップデート番号、その中のパッチまたはホットフィックス番号、公開日を表示します。',
    closing: '麦畑で過ごしてくださり、ありがとうございます。気になる不具合があれば、サポートの問題報告フォームから状況をお知らせください。',
  },
  es: {
    greeting: '¡Hola, viajeros!',
    releaseIntro: 'Ahora es más fácil orientarse en los trigales. Esta actualización trae una Guía de controles con búsqueda, un espacio para los ajustes y el soporte, y música tranquila para acompañar la lluvia.',
    patchIntro: 'Este parche devuelve los accesos habituales del menú a su sitio y te permite ajustar mejor lo que escuchas. Estos son los cambios.',
    features: 'Nuevas funciones y mejoras', refinements: 'Mejoras', navigation: 'Menús y navegación', audio: 'Sonido', guide: 'Guía de controles', support: 'Soporte',
    audioIntro: 'Deja que te acompañe la música o baja su volumen para escuchar el viento y la lluvia. Abre el engranaje y elige Sonido para encontrar los nuevos controles.',
    levels: 'Ajusta por separado el volumen general, la música, los sonidos de la naturaleza y los efectos. Los sonidos de la naturaleza incluyen viento, lluvia y pájaros lejanos; los efectos incluyen avisos del chat e interacciones con el cuadro.',
    mutes: 'Silencia cada categoría sin perder el volumen elegido. El silencio general apaga todo y conserva tus ajustes para cuando vuelvas a activar el sonido.',
    saved: 'Tus preferencias de sonido se conservan en este dispositivo al recargar la página o cambiar de cuadro.',
    shortcuts: 'Cambiar de cuadro y Amigos vuelven a estar debajo del botón para entrar en el cuadro. El engranaje conserva Idioma, Sonido, Ajustes de vuelo y Soporte; la Guía de controles sigue a su lado.',
    articles: 'Cambios ahora muestra artículos por versión, con un resumen y secciones por tema. Los títulos indican el tipo de publicación, el número de actualización, el número de parche o corrección urgente dentro de ella y la fecha.',
    closing: 'Gracias por pasar un rato en los trigales. Si algo no funciona bien, cuéntanos qué ha pasado mediante «Informar de un problema» en Soporte.',
  },
  fr: {
    greeting: 'Bonjour, voyageurs !',
    releaseIntro: 'Il devient plus facile de trouver ses repères dans les champs de blé. Cette mise à jour propose un Guide des commandes avec recherche, un espace pour les paramètres et l’assistance, ainsi qu’une musique douce pour accompagner la pluie.',
    patchIntro: 'Ce correctif remet les raccourcis habituels du menu à leur place et vous permet de mieux régler ce que vous entendez. Voici les changements.',
    features: 'Nouvelles fonctionnalités et améliorations', refinements: 'Améliorations', navigation: 'Menus et navigation', audio: 'Son', guide: 'Guide des commandes', support: 'Assistance',
    audioIntro: 'Laissez la musique vous accompagner, ou baissez-la pour écouter le vent et la pluie. Ouvrez l’engrenage, puis Son, pour trouver les nouveaux réglages.',
    levels: 'Réglez séparément le volume général, la musique, les sons de la nature et les effets sonores. La nature comprend le vent, la pluie et les oiseaux au loin ; les effets comprennent les notifications du chat et les interactions avec le tableau.',
    mutes: 'Coupez chaque catégorie sans perdre le volume choisi. Couper le son général rend tout silencieux, tout en conservant vos réglages pour le réactiver.',
    saved: 'Vos préférences sonores restent enregistrées sur cet appareil après un rechargement de la page ou un changement de tableau.',
    shortcuts: 'Changer de tableau et Amis retrouvent leur place sous le bouton d’entrée dans le tableau. L’engrenage conserve Langue, Son, Commandes de vol et Assistance ; le Guide des commandes reste à côté.',
    articles: 'Changements présente désormais des articles numérotés, avec un aperçu et des sections par thème. Les titres indiquent le type de publication, le numéro de mise à jour, le numéro du correctif ou correctif urgent au sein de celle-ci, et la date.',
    closing: 'Merci de passer du temps dans les champs de blé. Si quelque chose ne fonctionne pas, racontez-nous ce qui s’est passé via le formulaire de signalement dans Assistance.',
  },
  de: {
    greeting: 'Hallo, Reisende!',
    releaseIntro: 'In den Weizenfeldern findest du dich jetzt leichter zurecht. Dieses Update bringt eine durchsuchbare Steuerungsanleitung, einen gemeinsamen Einstieg für Einstellungen und Support sowie ruhige Musik zum Regen.',
    patchIntro: 'Dieser Patch bringt vertraute Menütasten an ihren Platz zurück und gibt dir mehr Kontrolle über den Klang. Das hat sich geändert.',
    features: 'Neue Funktionen und Verbesserungen', refinements: 'Verbesserungen', navigation: 'Menüs und Navigation', audio: 'Ton', guide: 'Steuerungsanleitung', support: 'Support',
    audioIntro: 'Lass dich von der Musik begleiten oder drehe sie leiser, um Wind und Regen zu hören. Öffne das Zahnrad und wähle Ton für die neuen Regler.',
    levels: 'Stelle Gesamtlautstärke, Musik, Naturgeräusche und Soundeffekte getrennt ein. Naturgeräusche umfassen Wind, Regen und ferne Vogelstimmen; Soundeffekte umfassen Chat-Benachrichtigungen und Interaktionen mit dem Gemälde.',
    mutes: 'Schalte jede Kategorie einzeln stumm, ohne die gewählte Lautstärke zu verlieren. Die allgemeine Stummschaltung hält alles still und bewahrt deine Einstellungen für das Wiedereinschalten.',
    saved: 'Deine Toneinstellungen bleiben auf diesem Gerät erhalten, auch wenn du die Seite neu lädst oder das Gemälde wechselst.',
    shortcuts: 'Gemälde wechseln und Freunde stehen wieder unter der Schaltfläche zum Betreten des Gemäldes. Im Zahnrad bleiben Sprache, Ton, Flugsteuerung und Support; die Steuerungsanleitung bleibt daneben.',
    articles: 'Änderungen zeigt jetzt nummerierte Artikel mit einem Überblick und Abschnitten nach Thema. Die Titel nennen die Art der Veröffentlichung, die Update-Nummer, die Patch- oder Hotfix-Nummer innerhalb dieses Updates und das Datum.',
    closing: 'Danke für deine Zeit in den Weizenfeldern. Wenn etwas nicht stimmt, erzähle uns über „Problem melden“ im Support, was passiert ist.',
  },
  nl: {
    greeting: 'Hallo, reizigers!',
    releaseIntro: 'Je weg vinden in de korenvelden wordt eenvoudiger. Deze update brengt een doorzoekbare Besturingsgids, een plek voor instellingen en ondersteuning, en rustige muziek bij de regen.',
    patchIntro: 'Deze patch zet vertrouwde menuknoppen terug op hun plek en geeft je meer controle over wat je hoort. Dit is er veranderd.',
    features: 'Nieuwe functies en verbeteringen', refinements: 'Verbeteringen', navigation: 'Menu’s en navigatie', audio: 'Geluid', guide: 'Besturingsgids', support: 'Ondersteuning',
    audioIntro: 'Laat de muziek je begeleiden of zet haar zachter om naar wind en regen te luisteren. Open het tandwiel en kies Geluid voor de nieuwe regelaars.',
    levels: 'Stel het algemene volume, muziek, natuurgeluiden en geluidseffecten apart in. Natuurgeluiden zijn wind, regen en vogels in de verte; geluidseffecten zijn chatmeldingen en interacties met het schilderij.',
    mutes: 'Demp elke categorie apart zonder het gekozen volume te verliezen. Met algemeen dempen zet je alles stil, terwijl je instellingen bewaard blijven voor wanneer je het geluid weer aanzet.',
    saved: 'Je geluidsvoorkeuren blijven op dit apparaat bewaard als je de pagina vernieuwt of van schilderij wisselt.',
    shortcuts: 'Van schilderij wisselen en Vrienden staan weer onder de knop om het schilderij binnen te gaan. Het tandwiel bevat Taal, Geluid, Vliegbesturing en Ondersteuning; de Besturingsgids blijft ernaast staan.',
    articles: 'Wijzigingen toont nu genummerde artikelen met een overzicht en onderdelen per onderwerp. De titels vermelden het soort release, het updatenummer, het patch- of hotfixnummer binnen die update en de datum.',
    closing: 'Bedankt dat je tijd doorbrengt in de korenvelden. Werkt iets niet zoals verwacht? Vertel ons wat er gebeurde via “Probleem melden” in Ondersteuning.',
  },
}
