import type { Lang } from './i18n'

const en = {
  support: 'Support', known: 'Known Issues', report: 'Report an issue',
  intro: 'Confirmed issues and the latest changes, all in one place.',
  empty: 'No confirmed issues have been published yet. Found something unexpected? Let us know.',
  loading: 'Loading issues…', loadError: 'We couldn’t load the issue list.', retry: 'Try again',
  submit: 'Send report', sending: 'Sending…', done: 'Done',
  thanks: 'Thank you for helping improve the wheatfields.',
  reviewNotice: 'Your report is saved for review. New issues will appear here once they have been confirmed. Reports about the same issue are grouped together.',
  duplicate: 'This report is already in the review queue.', reference: 'Report reference',
  invalid: 'Please describe what happened, what you expected, and how to reproduce it. Use a few clear words in each field.',
  limited: 'You’ve sent several reports. Please wait 10 minutes before sending another.',
  sendError: 'Your report wasn’t saved. Please try again. Your text is still here.',
  title: 'Short summary', description: 'What happened?', steps: 'How can we reproduce it?',
  expected: 'What did you expect to happen?', device: 'Device and browser', painting: 'Painting', all: 'All paintings / menu',
  privacy: 'Reports are private. Please don’t include passwords, contact details, or other personal information.',
  hint: 'Tell us what you tapped or pressed, and what happened next. A clear report makes it easier to check the problem.',
  investigating: 'Investigating', resolved: 'Resolved',
  updateMusic: 'Wheatfield with Crows now has a quiet cello-and-piano soundtrack made from recordings of real instruments, alongside the rain.',
  updateSupport: 'Support now includes known issues, update notes, and a private form for reporting problems. Reports are reviewed before new issues are published.',
  newFeature: "New feature",
  patch: "Patch",
  updateMusicTitle: "Music for the rain",
  updateSupportTitle: "Support",
  updateGuideTitle: "Controls Guide",
  changesFixes: "Changes and fixes",
  allDevices: "All devices",
  updateGuideDevices: "Renamed “How to play” to “Controls Guide” and grouped the instructions into Computer and Phone & tablet tabs.",
  updateGuideLanguage: "Reviewed the guide in all eight languages and clarified the wording while keeping the same instructions.",
  changes: "Changes",
  update: "Update",
  hotfix: "Hotfix",
  knownArticle: "Known issue",
  updateNavigationTitle: "Settings and guide search",
  updateSettingsHub: "The gear now opens a Settings hub for Language, Sound, Flight settings, and Support. Controls Guide remains a separate button on the main menu.",
  updateGuideSearch: "Each device tab in Controls Guide now has its own search. Topics are sorted alphabetically in the selected language, and the guide explains where to find everything in Settings.",
  updateSupportArticles: "The Support tab “Updates” is now called “Changes”. Changes and known issues appear as article buttons; select a title to read the full details.",
}
export type SupportCopy = Record<keyof typeof en, string>
export const SUPPORT_COPY: Record<Lang, SupportCopy> = {
  en,
  zhCN: {
    support: '支持', known: '已知问题', report: '反馈问题',
    intro: '在这里查看已确认的问题和最新更新。',
    empty: '暂时没有公布已确认的问题。遇到了意料之外的情况？欢迎告诉我们。',
    loading: '正在加载问题列表……', loadError: '暂时无法加载问题列表。', retry: '重试',
    submit: '提交反馈', sending: '正在提交……', done: '完成', thanks: '谢谢你帮助我们完善这片麦田。',
    reviewNotice: '反馈已保存，等待核查。新问题确认后会出现在这里，相同问题的反馈会合并整理。',
    duplicate: '这条反馈已经在待核查列表中。', reference: '反馈编号',
    invalid: '请清楚描述发生了什么、你期望的结果，以及重现问题的步骤。每一栏都请填写具体内容。',
    limited: '你已提交了几条反馈，请等 10 分钟后再试。', sendError: '反馈未能保存，请重试。你填写的内容仍在。',
    title: '问题简述', description: '发生了什么？', steps: '怎样重现这个问题？', expected: '你原本期望发生什么？',
    device: '设备和浏览器', painting: '画卷', all: '所有画卷／菜单',
    privacy: '反馈内容不会公开。请不要填写密码、联系方式或其他个人信息。',
    hint: '请说明你点了哪里、按了什么，以及随后发生的情况。描述越清楚，越方便核查。',
    investigating: '正在调查', resolved: '已解决',
    updateMusic: '《麦田群鸦》新增轻柔的大提琴与钢琴配乐，使用真实乐器录音，与雨声相伴。',
    updateSupport: '支持页面新增已知问题、更新说明和私密的问题反馈表。新问题经过核查后才会公布。',
    newFeature: "新增功能",
    patch: "修复补丁",
    updateMusicTitle: "雨中的音乐",
    updateSupportTitle: "支持",
    updateGuideTitle: "操作指南",
    changesFixes: "调整与修复",
    allDevices: "所有设备",
    updateGuideDevices: "将“漫游指南”更名为“操作指南”，按“电脑”和“手机与平板”分栏整理说明。",
    updateGuideLanguage: "检查了全部八种语言的指南，调整措辞，让说明更自然、清楚，原意保持不变。",
    changes: "变更",
    update: "更新",
    hotfix: "紧急修复",
    knownArticle: "已知问题",
    updateNavigationTitle: "设置与指南搜索",
    updateSettingsHub: "齿轮现在会打开设置主页，集中显示语言、声音、飞行设置和支持。操作指南仍是主菜单中的独立按钮。",
    updateGuideSearch: "操作指南的每个设备分页都新增了搜索栏，并按所选语言的字母或本地文字顺序排列主题。指南也说明了如何在设置中找到各项功能。",
    updateSupportArticles: "支持中的“更新”分页已更名为“变更”。变更和已知问题以文章按钮呈现，选择标题即可阅读详情。",
  },
  zhTW: {
    support: '支援', known: '已知問題', report: '回報問題',
    intro: '在這裡查看已確認的問題和最新更新。',
    empty: '目前尚未公布已確認的問題。遇到意料之外的情況嗎？歡迎告訴我們。',
    loading: '正在載入問題清單……', loadError: '暫時無法載入問題清單。', retry: '重試',
    submit: '送出回報', sending: '正在送出……', done: '完成', thanks: '謝謝你幫助我們完善這片麥田。',
    reviewNotice: '回報已儲存，等待查證。新問題確認後會出現在這裡，相同問題的回報會合併整理。',
    duplicate: '這份回報已在待查證清單中。', reference: '回報編號',
    invalid: '請清楚描述發生了什麼、你預期的結果，以及重現問題的步驟。每一欄都請填寫具體內容。',
    limited: '你已送出幾份回報，請等 10 分鐘後再試。', sendError: '回報未能儲存，請重試。你填寫的內容仍在。',
    title: '問題簡述', description: '發生了什麼？', steps: '如何重現這個問題？', expected: '你原本預期會發生什麼？',
    device: '裝置和瀏覽器', painting: '畫卷', all: '所有畫卷／選單',
    privacy: '回報內容不會公開。請勿填寫密碼、聯絡方式或其他個人資料。',
    hint: '請說明你點了哪裡、按了什麼，以及隨後發生的情況。描述越清楚，越方便查證。',
    investigating: '調查中', resolved: '已解決',
    updateMusic: '《麥田群鴉》新增輕柔的大提琴與鋼琴配樂，使用真實樂器錄音，與雨聲相伴。',
    updateSupport: '支援頁面新增已知問題、更新說明和私密的問題回報表。新問題經過查證後才會公布。',
    newFeature: "新增功能",
    patch: "修正更新",
    updateMusicTitle: "雨中的音樂",
    updateSupportTitle: "支援",
    updateGuideTitle: "操作指南",
    changesFixes: "調整與修正",
    allDevices: "所有裝置",
    updateGuideDevices: "將「漫遊指南」更名為「操作指南」，按「電腦」和「手機與平板」分頁整理說明。",
    updateGuideLanguage: "檢查了全部八種語言的指南，調整措辭，讓說明更自然、清楚，原意保持不變。",
    changes: "變更",
    update: "更新",
    hotfix: "緊急修正",
    knownArticle: "已知問題",
    updateNavigationTitle: "設定與指南搜尋",
    updateSettingsHub: "齒輪現在會開啟設定首頁，集中顯示語言、聲音、飛行設定和支援。操作指南仍是主選單中的獨立按鈕。",
    updateGuideSearch: "操作指南的每個裝置分頁都新增了搜尋欄，並依所選語言的字母或本地文字順序排列主題。指南也說明了如何在設定中找到各項功能。",
    updateSupportArticles: "支援中的「更新」分頁已更名為「變更」。變更和已知問題以文章按鈕呈現，選擇標題即可閱讀詳情。",
  },
  ja: {
    support: 'サポート', known: '確認されている不具合', report: '不具合を報告',
    intro: '確認済みの不具合と最新の変更内容をご案内します。',
    empty: '現在、公開されている確認済みの不具合はありません。気になることがあればお知らせください。',
    loading: '読み込み中…', loadError: '不具合の一覧を読み込めませんでした。', retry: '再試行',
    submit: '報告を送信', sending: '送信中…', done: '完了', thanks: '麦畑をよりよくするためのご協力、ありがとうございます。',
    reviewNotice: '報告を受け付けました。内容を確認し、新たな不具合と確認できた場合はここに掲載します。同じ不具合の報告はまとめて扱います。',
    duplicate: 'この報告はすでに確認待ちです。', reference: '受付番号',
    invalid: '起きたこと、期待していた動作、再現するための手順を、それぞれ具体的に記入してください。',
    limited: '短時間に複数の報告が送信されました。10分ほど待ってからお試しください。', sendError: '報告を保存できませんでした。入力内容は残っていますので、もう一度お試しください。',
    title: '問題の概要', description: '何が起きましたか？', steps: 'どのような操作で再現しますか？', expected: '本来はどうなると思いましたか？',
    device: '端末とブラウザー', painting: '絵画', all: 'すべての絵画／メニュー',
    privacy: '報告内容は公開されません。パスワード、連絡先などの個人情報は記入しないでください。',
    hint: 'タップした場所や押したキー、その後に起きたことを教えてください。具体的な手順があると確認しやすくなります。',
    investigating: '調査中', resolved: '解決済み',
    updateMusic: '「カラスのいる麦畑」に、本物の楽器の録音を使った静かなチェロとピアノの音楽を追加しました。雨音とともに流れます。',
    updateSupport: 'サポートに不具合情報、更新情報、非公開の報告フォームを追加しました。新しい不具合は確認後に掲載します。',
    newFeature: "新機能",
    patch: "修正パッチ",
    updateMusicTitle: "雨に寄り添う音楽",
    updateSupportTitle: "サポート",
    updateGuideTitle: "操作ガイド",
    changesFixes: "変更・修正内容",
    allDevices: "すべての端末",
    updateGuideDevices: "「遊び方」を「操作ガイド」に変更し、「パソコン」と「スマホとタブレット」のタブに分けて操作方法をまとめました。",
    updateGuideLanguage: "全8言語のガイドを見直し、説明の意味を変えずに、より自然で分かりやすい表現に整えました。",
    changes: "変更履歴",
    update: "アップデート",
    hotfix: "緊急修正",
    knownArticle: "確認されている不具合",
    updateNavigationTitle: "設定とガイドの検索",
    updateSettingsHub: "歯車から開く設定画面に、言語、サウンド、飛行設定、サポートをまとめました。操作ガイドはメインメニューの独立したボタンから開けます。",
    updateGuideSearch: "操作ガイドの端末別タブに、それぞれ検索欄を追加しました。項目は選択した言語に合った順序で並びます。設定の各機能への行き方も説明しています。",
    updateSupportArticles: "サポートの「アップデート」タブを「変更履歴」に変更しました。変更内容や確認されている不具合のタイトルを選ぶと、詳しい記事が開きます。",
  },
  es: {
    support: 'Soporte', known: 'Problemas conocidos', report: 'Informar de un problema',
    intro: 'Consulta los problemas confirmados y los últimos cambios.',
    empty: 'Todavía no se han publicado problemas confirmados. ¿Has encontrado algo inesperado? Cuéntanoslo.',
    loading: 'Cargando problemas…', loadError: 'No se pudo cargar la lista.', retry: 'Reintentar',
    submit: 'Enviar informe', sending: 'Enviando…', done: 'Listo', thanks: 'Gracias por ayudarnos a mejorar los trigales.',
    reviewNotice: 'Hemos guardado tu informe para revisarlo. Los problemas nuevos aparecerán aquí cuando se confirmen. Los informes del mismo problema se agruparán.',
    duplicate: 'Este informe ya está pendiente de revisión.', reference: 'Número de informe',
    invalid: 'Describe con claridad qué pasó, qué esperabas y cómo reproducirlo. Completa cada campo con detalles concretos.',
    limited: 'Has enviado varios informes. Espera 10 minutos antes de enviar otro.', sendError: 'No se guardó el informe. Inténtalo de nuevo; tu texto sigue aquí.',
    title: 'Resumen breve', description: '¿Qué ocurrió?', steps: '¿Cómo podemos reproducirlo?', expected: '¿Qué esperabas que ocurriera?',
    device: 'Dispositivo y navegador', painting: 'Cuadro', all: 'Todos los cuadros / menú',
    privacy: 'Los informes son privados. No incluyas contraseñas, datos de contacto ni otra información personal.',
    hint: 'Indica qué tocaste o qué tecla pulsaste y qué ocurrió después. Los detalles nos ayudan a comprobar el problema.',
    investigating: 'En investigación', resolved: 'Resuelto',
    updateMusic: 'Campo de trigo con cuervos tiene ahora una tranquila banda sonora de violonchelo y piano, creada con grabaciones de instrumentos reales que acompañan la lluvia.',
    updateSupport: 'Soporte incluye problemas conocidos, notas de actualización y un formulario privado para informar de problemas. Los nuevos problemas se publican después de revisarlos.',
    newFeature: "Nueva función",
    patch: "Parche",
    updateMusicTitle: "Música para la lluvia",
    updateSupportTitle: "Soporte",
    updateGuideTitle: "Guía de controles",
    changesFixes: "Cambios y correcciones",
    allDevices: "Todos los dispositivos",
    updateGuideDevices: "«Cómo jugar» pasa a llamarse «Guía de controles». Las instrucciones se agrupan en las pestañas «Ordenador» y «Móvil y tableta».",
    updateGuideLanguage: "Se ha revisado la guía en los ocho idiomas para que suene más natural y resulte más clara, sin cambiar el significado de las instrucciones.",
    changes: "Cambios",
    update: "Actualización",
    hotfix: "Corrección urgente",
    knownArticle: "Problema conocido",
    updateNavigationTitle: "Ajustes y búsqueda en la guía",
    updateSettingsHub: "El engranaje abre ahora una página de Ajustes con Idioma, Sonido, Ajustes de vuelo y Soporte. La Guía de controles mantiene su propio botón en el menú principal.",
    updateGuideSearch: "Cada pestaña de dispositivo de la Guía de controles tiene su propio buscador. Los temas se ordenan alfabéticamente según el idioma seleccionado, y la guía explica dónde encontrar cada función en Ajustes.",
    updateSupportArticles: "La pestaña «Novedades» de Soporte se llama ahora «Cambios». Los cambios y problemas conocidos aparecen como botones con el título del artículo; selecciónalos para leer todos los detalles.",
  },
  fr: {
    support: 'Assistance', known: 'Problèmes connus', report: 'Signaler un problème',
    intro: 'Retrouvez les problèmes confirmés et les dernières nouveautés.',
    empty: 'Aucun problème confirmé n’a encore été publié. Vous avez remarqué quelque chose d’inhabituel ? Faites-le-nous savoir.',
    loading: 'Chargement des problèmes…', loadError: 'Impossible de charger la liste.', retry: 'Réessayer',
    submit: 'Envoyer le signalement', sending: 'Envoi en cours…', done: 'Terminé', thanks: 'Merci de nous aider à améliorer les champs de blé.',
    reviewNotice: 'Votre signalement a été enregistré pour examen. Les nouveaux problèmes apparaîtront ici après confirmation. Les signalements concernant le même problème seront regroupés.',
    duplicate: 'Ce signalement est déjà en attente d’examen.', reference: 'Numéro du signalement',
    invalid: 'Décrivez clairement ce qui s’est passé, le résultat attendu et les étapes pour reproduire le problème. Précisez chaque champ.',
    limited: 'Vous avez envoyé plusieurs signalements. Veuillez patienter 10 minutes avant d’en envoyer un autre.', sendError: 'Le signalement n’a pas été enregistré. Réessayez : votre texte est toujours là.',
    title: 'Résumé du problème', description: 'Que s’est-il passé ?', steps: 'Comment reproduire le problème ?', expected: 'Quel résultat attendiez-vous ?',
    device: 'Appareil et navigateur', painting: 'Tableau', all: 'Tous les tableaux / menu',
    privacy: 'Les signalements sont privés. N’incluez pas de mots de passe, de coordonnées ou d’autres informations personnelles.',
    hint: 'Indiquez où vous avez appuyé ou quelle touche vous avez utilisée, puis ce qui s’est passé. Ces détails facilitent la vérification.',
    investigating: 'En cours d’examen', resolved: 'Résolu',
    updateMusic: 'Champ de blé aux corbeaux s’accompagne désormais d’une musique douce au violoncelle et au piano, créée à partir d’enregistrements de vrais instruments, sur fond de pluie.',
    updateSupport: 'L’assistance propose les problèmes connus, les notes de mise à jour et un formulaire privé de signalement. Les nouveaux problèmes sont publiés après vérification.',
    newFeature: "Nouvelle fonctionnalité",
    patch: "Correctif",
    updateMusicTitle: "Musique sous la pluie",
    updateSupportTitle: "Assistance",
    updateGuideTitle: "Guide des commandes",
    changesFixes: "Modifications et corrections",
    allDevices: "Tous les appareils",
    updateGuideDevices: "« Comment jouer » devient « Guide des commandes ». Les instructions sont regroupées dans les onglets « Ordinateur » et « Téléphone et tablette ».",
    updateGuideLanguage: "Le guide a été revu dans les huit langues pour rendre les formulations plus naturelles et plus claires, sans changer le sens des instructions.",
    changes: "Changements",
    update: "Mise à jour",
    hotfix: "Correctif urgent",
    knownArticle: "Problème connu",
    updateNavigationTitle: "Paramètres et recherche dans le guide",
    updateSettingsHub: "L’engrenage ouvre désormais une page de paramètres regroupant Langue, Son, Commandes de vol et Assistance. Le Guide des commandes conserve son propre bouton dans le menu principal.",
    updateGuideSearch: "Chaque onglet d’appareil du Guide des commandes dispose de sa propre recherche. Les rubriques sont classées par ordre alphabétique selon la langue choisie, et le guide explique où trouver chaque fonction dans les paramètres.",
    updateSupportArticles: "L’onglet « Mises à jour » de l’assistance s’appelle désormais « Changements ». Les changements et les problèmes connus apparaissent sous forme de boutons portant le titre de l’article. Sélectionnez un titre pour lire les détails.",
  },
  de: {
    support: 'Support', known: 'Bekannte Probleme', report: 'Problem melden',
    intro: 'Bestätigte Probleme und die neuesten Änderungen an einem Ort.',
    empty: 'Bisher wurden keine bestätigten Probleme veröffentlicht. Ist dir etwas Unerwartetes aufgefallen? Sag uns Bescheid.',
    loading: 'Probleme werden geladen…', loadError: 'Die Liste konnte nicht geladen werden.', retry: 'Erneut versuchen',
    submit: 'Meldung senden', sending: 'Wird gesendet…', done: 'Fertig', thanks: 'Danke, dass du uns hilfst, die Weizenfelder zu verbessern.',
    reviewNotice: 'Deine Meldung wurde zur Prüfung gespeichert. Neue Probleme erscheinen hier, sobald sie bestätigt sind. Meldungen zum selben Problem werden zusammengefasst.',
    duplicate: 'Diese Meldung wartet bereits auf Prüfung.', reference: 'Meldungsnummer',
    invalid: 'Beschreibe, was passiert ist, was du erwartet hast und wie sich das Problem wiederholen lässt. Fülle jedes Feld mit konkreten Angaben aus.',
    limited: 'Du hast mehrere Meldungen gesendet. Warte bitte 10 Minuten, bevor du eine weitere sendest.', sendError: 'Die Meldung wurde nicht gespeichert. Versuche es erneut; dein Text ist noch da.',
    title: 'Kurze Zusammenfassung', description: 'Was ist passiert?', steps: 'Wie können wir das Problem nachstellen?', expected: 'Was hätte passieren sollen?',
    device: 'Gerät und Browser', painting: 'Gemälde', all: 'Alle Gemälde / Menü',
    privacy: 'Meldungen sind privat. Bitte gib keine Passwörter, Kontaktdaten oder anderen persönlichen Informationen an.',
    hint: 'Beschreibe, was du angetippt oder welche Taste du gedrückt hast und was danach passiert ist. Klare Angaben helfen bei der Prüfung.',
    investigating: 'Wird untersucht', resolved: 'Behoben',
    updateMusic: 'Weizenfeld mit Krähen hat jetzt eine ruhige Begleitung aus Cello und Klavier. Sie besteht aus Aufnahmen echter Instrumente und ergänzt den Regen.',
    updateSupport: 'Im Support findest du bekannte Probleme, Neuigkeiten und ein privates Formular zum Melden von Fehlern. Neue Probleme werden erst nach Prüfung veröffentlicht.',
    newFeature: "Neue Funktion",
    patch: "Patch",
    updateMusicTitle: "Musik im Regen",
    updateSupportTitle: "Support",
    updateGuideTitle: "Steuerungsanleitung",
    changesFixes: "Änderungen und Korrekturen",
    allDevices: "Alle Geräte",
    updateGuideDevices: "„So spielst du“ heißt jetzt „Steuerungsanleitung“. Die Anweisungen sind nach „Computer“ und „Handy und Tablet“ geordnet.",
    updateGuideLanguage: "Die Anleitung wurde in allen acht Sprachen auf natürlichere und klarere Formulierungen geprüft. Die Bedeutung der Anweisungen bleibt erhalten.",
    changes: "Änderungen",
    update: "Update",
    hotfix: "Hotfix",
    knownArticle: "Bekanntes Problem",
    updateNavigationTitle: "Einstellungen und Suche in der Anleitung",
    updateSettingsHub: "Das Zahnrad öffnet jetzt eine Einstellungsübersicht mit Sprache, Ton, Flugsteuerung und Support. Die Steuerungsanleitung behält ihre eigene Schaltfläche im Hauptmenü.",
    updateGuideSearch: "Jeder Geräte-Tab der Steuerungsanleitung hat eine eigene Suche. Die Themen sind entsprechend der gewählten Sprache alphabetisch sortiert. Die Anleitung erklärt auch, wo du die Funktionen in den Einstellungen findest.",
    updateSupportArticles: "Der Support-Tab „Neuigkeiten“ heißt jetzt „Änderungen“. Änderungen und bekannte Probleme erscheinen als Schaltflächen mit Artikeltiteln. Wähle einen Titel, um alle Details zu lesen.",
  },
  nl: {
    support: 'Ondersteuning', known: 'Bekende problemen', report: 'Probleem melden',
    intro: 'Bevestigde problemen en de nieuwste veranderingen op één plek.',
    empty: 'Er zijn nog geen bevestigde problemen gepubliceerd. Gebeurt er iets onverwachts? Laat het ons weten.',
    loading: 'Problemen laden…', loadError: 'De lijst kon niet worden geladen.', retry: 'Opnieuw proberen',
    submit: 'Melding versturen', sending: 'Versturen…', done: 'Klaar', thanks: 'Bedankt dat je helpt de korenvelden te verbeteren.',
    reviewNotice: 'Je melding is opgeslagen om te worden nagekeken. Nieuwe problemen verschijnen hier zodra ze bevestigd zijn. Meldingen over hetzelfde probleem worden samengevoegd.',
    duplicate: 'Deze melding wacht al op beoordeling.', reference: 'Meldingsnummer',
    invalid: 'Beschrijf duidelijk wat er gebeurde, wat je verwachtte en hoe we het kunnen herhalen. Geef bij elk veld concrete details.',
    limited: 'Je hebt meerdere meldingen verstuurd. Wacht 10 minuten voordat je er nog een verstuurt.', sendError: 'Je melding is niet opgeslagen. Probeer het opnieuw; je tekst staat er nog.',
    title: 'Korte samenvatting', description: 'Wat gebeurde er?', steps: 'Hoe kunnen we het probleem herhalen?', expected: 'Wat had je verwacht?',
    device: 'Apparaat en browser', painting: 'Schilderij', all: 'Alle schilderijen / menu',
    privacy: 'Meldingen zijn privé. Vermeld geen wachtwoorden, contactgegevens of andere persoonlijke informatie.',
    hint: 'Vertel waarop je tikte of welke toets je indrukte en wat er daarna gebeurde. Met duidelijke stappen kunnen we het probleem beter controleren.',
    investigating: 'In onderzoek', resolved: 'Opgelost',
    updateMusic: 'Korenveld met kraaien heeft nu rustige muziek voor cello en piano, gemaakt met opnamen van echte instrumenten en begeleid door de regen.',
    updateSupport: 'Ondersteuning bevat bekende problemen, updates en een privéformulier om problemen te melden. Nieuwe problemen worden pas na controle gepubliceerd.',
    newFeature: "Nieuwe functie",
    patch: "Patch",
    updateMusicTitle: "Muziek in de regen",
    updateSupportTitle: "Ondersteuning",
    updateGuideTitle: "Besturingsgids",
    changesFixes: "Wijzigingen en verbeteringen",
    allDevices: "Alle apparaten",
    updateGuideDevices: "“Zo speel je” heet nu “Besturingsgids”. De uitleg is verdeeld over de tabbladen “Computer” en “Telefoon en tablet”.",
    updateGuideLanguage: "De gids is in alle acht talen nagekeken en natuurlijker en duidelijker verwoord, zonder de betekenis van de instructies te veranderen.",
    changes: "Wijzigingen",
    update: "Update",
    hotfix: "Hotfix",
    knownArticle: "Bekend probleem",
    updateNavigationTitle: "Instellingen en zoeken in de gids",
    updateSettingsHub: "Het tandwiel opent nu een overzicht met Taal, Geluid, Vliegbesturing en Ondersteuning. De Besturingsgids houdt een eigen knop in het hoofdmenu.",
    updateGuideSearch: "Elk apparaattabblad in de Besturingsgids heeft een eigen zoekveld. De onderwerpen staan op alfabetische volgorde volgens de gekozen taal. De gids legt ook uit waar je alle functies in Instellingen vindt.",
    updateSupportArticles: "Het tabblad “Updates” in Ondersteuning heet nu “Wijzigingen”. Wijzigingen en bekende problemen verschijnen als knoppen met artikeltitels. Kies een titel om alle details te lezen.",
  },
}
